# Generated by Django 3.2.3 on 2022-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainitem',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
