# Generated by Django 3.2.9 on 2021-11-26 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0002_rename_datetime_item_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
